### ISSUE TITLE
We should leverage apscheduler lib to schedule events and drop dependency on amlight/scheduler

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/sdntrace_cp#15]
As discussed before, there is no reason for depending on another Napp - `amlight/scheduler` - just for scheduling events.

We can leverage apscheduler lib and remove the dependency on amlight/scheduler.

Similar usage of apscheduler can be seen at kytos-ng/maintenance: https://github.com/kytos-ng/maintenance/blob/master/models.py#L204-L230

**Comment by viniarck** [comment]
> Since we already have apscheduler running into Maintenance and we are discussing about using it also in sdntrace-cp, maybe it does make sense to have a very simple Napp just for doing so. The is aligned with the micro-service concept of Kytos. What do you think, @viniarck and @ajoaoff ?

@italovalcy sorry for the late reply, I missed this notification. This idea is an option and is aligned how things are structured, but I think it can ended up in a leaky abstraction or too difficult to maintain making error handling harder than usual and wrapping a library that's too flexible and broad. `apscheduler` can also support a backend to store job results (we might use MongoDB for certain cases in the future) and retrieve result and different executors, and provides a full blown job scheduling interface that we aren't using that thoroughly, it reminds me of challenges that we've faced with storehouse, although if we were to wrap on endpoints that partly solves some challenges of error handling, but maintain a lot of endpoints wrapping most things that are needed or will be needed can be costly development-wise.

A general guideline for abstracting a functionality in a NApp I think we can try to follow and document better is, if it's providing a network related functionality or if it's abstracting significant logic, owning common settings or resources, performing a significant third-party integration and not just wrapping a library that's mainly performing things in memory, if it's mainly a wrapper of a library like `apscheduler` or `requests` (or similar lightweight ones), then it's likely not worth the effort to maintain a full blown NApp for it, considering that currently our development team is relatively small as well. For cases where we need to reuse these library-like abstractions I'd suggest extracting new libraries on `pypi` that we could maintain instead of a NApp (when it's not worth shipping with kytos core), and we can keep moving towards this direction gradually as needed. Also, similarly to what we've done for kytos core support for MongoDB driver, we can also assess for some cases to shipping a common heavily used library in the core at the expense of bloating it slightly, the effort to maintain fewer NApps and that are easier to use it's probably worth the trade-off. 

Let me know your thoughts, it's difficult to draw these boundaries when a new NApp or what we're meaning by microservice, and at to some extent without much general guidelines document it's even harder to discuss these microservices/NApps boundaries. We can also discuss in a call if you prefer or if you see any other benefits that outweigh the effort/cons, thanks for your suggestion.

**Comment by italovalcy** [comment]
> certain cases in the future) and retrieve result and different executors, and provides a full blown job scheduling interface that we aren't using that thoroughly

Hi @viniarck, sounds good to me! You are right, I believe the proposed guideline for abstracting a Napp is a good suggestion. Let's pursue the proposed approach!

**Comment by viniarck** [comment]
I'll go ahead and close this. Landed on #36
