### ISSUE TITLE
feat: Check that `dl_vlan` has a valid value.

### ISSUE THREAD

**Issue by gretelliz** [kytos-ng/sdntrace_cp#84]
This is for validate that `dl_vlan` (in a packet) is an integer in range [1, 4095] as discussed in PR #82.
If an untagged packet needs to be sent, only a packet without dl_vlan should be allowed and not the integer zero.

**Comment by viniarck** [comment]
@gretelliz thanks for mapping this and making the requirements clear here, the validation let's cover it in the spec though that's also scheduled for this version on issue https://github.com/kytos-ng/sdntrace_cp/issues/63, OK? No need to add a temporary specific validation for this since we'll have `@validate` decorator moved to core and eventually you'd be able to use here on `sdntrace_cp`. So, updating the openapi.yml and adding the decorator should suffice.

**Comment by viniarck** [comment]
@gretelliz can we close this since the PR has landed?
